name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        # Include amd64 on all platforms.
        goos: [linux]
        goarch: [amd64,  arm64]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2.4.0
      - name: Show workflow information 
        id: get_filename
        run: |
          export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOARM$GOMIPS\"].friendlyName" -r < .github/build/friendly-filenames.json)
          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM, GOMIPS: $GOMIPS, RELEASE_NAME: $_NAME"
          echo "::set-output name=ASSET_NAME::$_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV
    
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18.2
      - name: Get project dependencies
        run: go mod download
      - name: Build Server
        run: |
          mkdir -p build_assets
          go build -v -o build_assets/Aiko-Server -trimpath -ldflags "-s -w" ./cmd/server
      - name: Build Mips softfloat Server
        if: matrix.goarch == 'mips' || matrix.goarch == 'mipsle'
        run: |
            GOMIPS=softfloat go build -v -o build_assets/Aiko-Server-softfloat -trimpath -ldflags "-s -w" ./cmd/server
      - name: Rename Windows Server
        if: matrix.goos == 'windows'
        run: |
          cd ./build_assets || exit 1
          mv Aiko-Server Aiko-Server.exe
      - name: Prepare to release
        run: |
          cp ${GITHUB_WORKSPACE}/README.md ./build_assets/README.md
          cp ${GITHUB_WORKSPACE}/LICENSE ./build_assets/LICENSE
      - name: Create ZIP archive
        shell: bash
        run: |
          pushd build_assets || exit 1
          touch -mt $(date +%Y01010000) *
          zip -9vr ../Aiko-Server-$ASSET_NAME.zip .
          popd || exit 1
          FILE=./Aiko-Server-$ASSET_NAME.zip
          DGST=$FILE.dgst
          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done
      - name: Change the name
        run: |
          mv build_assets Aiko-Server-$ASSET_NAME
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Aiko-Server-${{ steps.get_filename.outputs.ASSET_NAME }}
          path: |
            ./Aiko-Server-${{ steps.get_filename.outputs.ASSET_NAME }}/*
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: ./Aiko-Server-${{ steps.get_filename.outputs.ASSET_NAME }}.zip*
          tag: ${{ github.ref }}
          file_glob: true
         
